### ISSUE TITLE
Réarranger les bouts de code en bordel dans l'asser

### ISSUE THREAD

**Issue by Salamandar** [robotronik/asservissement#1]
- communication.\* | reception.\* fusionnent.
- uart.\* dégage (les fonctions sont déjà définies dans hardware_pic, donc à déplacer là).
- slow_read, demo dans un dépôt adéquat.
- hardware et reglages doivent être renommés *_sdl et/ou *_pic, et ces fichiers doivent être utilisés en fonction des options du Makefile
- Dans l'idéal, l'appel à la SDL doit être fait dans ces fichiers uniquement.

**Comment by robinmoussu** [comment]
- communication.\* | reception.\* fusionnent.

Fait.
- uart.\* dégage (les fonctions sont déjà définies dans hardware_pic, donc à déplacer là).

Le code dans common_code/communication ne l'utilise plus

**Comment by robinmoussu** [comment]
- uart.\* dégage

Fait.

**Comment by Salamandar** [comment]
- hardware et reglages doivent être renommés *_sdl et/ou *_pic, et ces fichiers doivent être utilisés en fonction des options du Makefile
  Fait !

**Comment by Salamandar** [comment]
Il faudrait virer la dépendance à la sdl dans odometrie.c (Robin c'est toi qui l'as rajoutée il y a longtemps).
Pareil, le sdl_manage_events() pourrait être appelé dans match_get_etat()… ou autre part.

De toute façon on peut fermer l'issue.
