### ISSUE TITLE
organisation des fichiers hardware + build

### ISSUE THREAD

**Issue by robinmoussu** [robotronik/asservissement#11]
Il faudrait réorganiser les fichiers hardware et le système de build, comme dans
le repo common_code.

Ce qui donnerai :

```
asservissement
├── build
│   └── $(ARCH)
│       └── $(DEBUG)
│           ├── *.o
│           └── binaire
│
│  ...
│
├── hardware
│   ├── PC
│   │   └── fichier_*.c
│   ├── PIC
│   │   └── fichier_*.c
│   └── STM32
│   │   └── fichier_*.c
└── fichier_*.h
```

**Comment by larchuto** [comment]
J'ai fait une branche avec la même chose pour les fichiers de réglages. Il faut que vous me disiez ce que vous en pensez.

**Comment by Salamandar** [comment]
J'ai fait une branche pour la réorganisation des Makefile, en partant sur la piste que tu avais lancée (@robinmoussu). Et ce sur tous les dépôts.

Finalement, en voyant que ça fonctionnait bien, et que ça convenait à Johan, ça a été mergé. Désolé de pas en avoir discuté avec toi avant ^^''

Du coup, je ferme cette issue.
