### ISSUE TITLE
Merger ce qu'il y a à merger

### ISSUE THREAD

**Issue by Salamandar** [robotronik/asservissement#13]
Dans l'état dans lequel c'est, je pense qu'il y avait master sur les robots au lieu de a_merger.
'faudrait voir (@Johan) ce qu'il faut merger, ou non :)
Il faut aussi voir avec Maxime ce qu'il a sur son pc (il y a eu des modifs, j'ai re-réglé le gros robot, ne sachant pas que les réglages avaient été faits sur une autre branche).

**Comment by robinmoussu** [comment]
Pour moi tout est mergé.

On 20/05/2015 02:36, Salamandar wrote:

> Dans l'état dans lequel c'est, je pense qu'il y avait master sur les
> robots au lieu de a_merger.
> 'faudrait voir (@Johan https://github.com/Johan) ce qu'il faut merger,
> ou non :)
> Il faut aussi voir avec Maxime ce qu'il a sur son pc (il y a eu des
> modifs, j'ai re-réglé le gros robot, ne sachant pas que les réglages
> avaient été faits sur une autre branche).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/robotronik/asservissement/issues/13.

## 

Robin Moussu

**Comment by johan** [comment]
Ici @johan. This is not the droid you are seeking. github + @<name> = notifications. :-)

**Comment by Salamandar** [comment]
@johan Sorry, bad droid in fact  ^^''
@larchuto, 'faut voir ce qu'il y a à merger, essentiellement dans les réglages.

**Comment by larchuto** [comment]
Ça explique pourquoi l'asser du petit robot ne répondait pas à ce qui lui était envoyé par UART… Et pourquoi les réglages du petit n'étaient plus là…

**Comment by Salamandar** [comment]
Non. Parce que j'ai flashé le gros avec le même code que le petit, et il répondait bien.
