### ISSUE TITLE
[emission] indiquer que le robot à atteind le point voulu

### ISSUE THREAD

**Issue by robinmoussu** [robotronik/asservissement#3]
Lorsque le robot atteind sa destination, il faudrait qu'il ait la possibilité de l'indiquer.

proposition : assert_done()

remarque : un simple message passé par printf() suffit, il faudra juste regrouper tout la gestion des message à un endroit

**Comment by larchuto** [comment]
Tout est près il suffit de remplacer l'appel à "debug()" dans "send_position_atteinte()" par la vraie fonction d'envoi
