### ISSUE TITLE
[emission] connaitre l'état de l'asservissement

### ISSUE THREAD

**Issue by robinmoussu** [robotronik/asservissement#4]
La partie stratégie pourra avoir besoin de connaitre l'état de l'asservissement.
- position
- commande en cour (chemin, déplacement, ...)

Remarque : comme précisé dans le ticket #3, un simple message passé par printf() suffit, il faudra juste regrouper tout la gestion des message à un endroit

**Comment by robinmoussu** [comment]
C'est en partie un doublon de #7. Est ce que la connaissance de la commande en cour est quelque chose d'utile ?

**Comment by larchuto** [comment]
Non perso je pense pas

Robin Moussu notifications@github.com a écrit :
