### ISSUE TITLE
emmergency stop

### ISSUE THREAD

**Issue by robinmoussu** [robotronik/asservissement#5]
À la fin du match, et en cas d'urgence, on va avoir besoin de faire piller le robot :

```
emergency_stop()
```

Je m'occupe de faire le wrappeur pour la communication dès que le code de l'assert sera prêt.

**Comment by larchuto** [comment]
Il l'est !

**Comment by Salamandar** [comment]
Et l'émission est prête :)

**Comment by robinmoussu** [comment]
il me faudrait le nom de la fonction a appeler. Est ce que c'est motor_stop() dans hardware.h (pas de doc pour la différencier de soft_stop().
