### ISSUE TITLE
calibration

### ISSUE THREAD

**Issue by robinmoussu** [robotronik/asservissement#6]
Ajouter une commande permetant de définir
- x
- y
- theta

pour l'asser.

**Comment by larchuto** [comment]
Les setters sont ajoutés dans l'odométrie

**Comment by Salamandar** [comment]
L'émission du message de calibration est prête !

**Comment by robinmoussu** [comment]
Intégré dans la communication.
Félix, tu t'occupe d'ajouter les lignes
    s2a_send_message(S2A_KEY_X, x);
    s2a_send_message(S2A_KEY_Y, y);
    s2a_send_message(S2A_KEY_THETA, theta);
    s2a_send_message(S2A_FCT_SET_POS);
au bon endroit dans la strategie (et avec les bonnes valeurs de x,y et theta^^).

**Comment by Salamandar** [comment]
Yes !
