### ISSUE TITLE
Connaitre la position du robot

### ISSUE THREAD

**Issue by robinmoussu** [robotronik/asservissement#7]
Ajouter une fonction permettant à la stratégie de connaitre à tout moment
- x
- y
- theta

**Comment by larchuto** [comment]
pour celà il faut utiliser les getteurs dispo dans l'odométrie :
- get_x_actuel()
- get_y_actuel()
- get_theta_actuel()

**Comment by robinmoussu** [comment]
Le code ne devrait pas être très différent de celui de la commande update() de toute façon.

**Comment by Salamandar** [comment]
Niveau émission, les fonction "where are you" et "i am here" on été mises en place.

**Comment by robinmoussu** [comment]
Code prêt au niveau de la communication.
Pushé sur a_integrer/communication des repos assert et common_code.
J'ai pas eu le temps de merger, je ferais ça ce soir.

Félix, regarde dans le fichier
    communication/s2a.c
Il y a deux lignes
    debug(_ERROR_, "TODO: appeler le code de la stratégie ici");
qu'il faut  que tu complète.

**Comment by Salamandar** [comment]
OK, vu ! Je ferme l'issue, maintenant que les fonctions adéquates ont été créées.
