### ISSUE TITLE
[reception] stop

### ISSUE THREAD

**Issue by robinmoussu** [robotronik/asservissement#9]
La commande d'arrêt (douce) n'est pas implémenté dans la reception.

**Comment by larchuto** [comment]
Du point de vue de l'asser désormais tout est près reste juste la réception

**Comment by Salamandar** [comment]
Et l'émission est prête :)

**Comment by robinmoussu** [comment]
@Salamandar Est ce que tu peux me donner le nom de la fonction que tu utilise pour faire stop(), stp

**Comment by Salamandar** [comment]
C'est pas à moi qu'il faut demander ça :p

**Comment by larchuto** [comment]
set_trajectoire_stop()
set_trajectoire_emergency_stop()
